services:
    - type: web
      name: gas-bill-fetcher-api
      env: docker
      plan: standard
      envVars:
        - key: NODE_ENV
          value: production
        - key: PORT
          value: 8080
        - key: GOOGLE_SHEET_ID
          sync: false
        - key: GOOGLE_CREDENTIALS_BASE64
          sync: false
        - key: BRIGHT_DATA_PROXY
          value: brd.superproxy.io:33335
        - key: BRIGHT_DATA_USER
          sync: false
        - key: BRIGHT_DATA_PASS
          sync: false
  